### ISSUE TITLE
Can't get subdomains to update

### ISSUE THREAD

**Issue by inertia666** [vic1707/Namesilo-DDNS-updater#1]
The script works fine to update the main A record but I cannot get subdomains to work either using * or by writing them in the hosts list.

I tried the following in .env to update the ip of three subdomains:

DOMAINS="mydomain.org"

## * means all subdomains.
# list separated by a comma
HOSTS="s1,s2,s3"

But it doesn't work either.

How do i update "s1.mydomain.org" etc?

**Comment by vic1707** [comment]
Hello, didn't got time yesterday to look at it, is the problem fixed? What was the cause?
